### PR TITLE
Remove main from footer

### LINKED ISSUE #7: Remove the class main on the div with a class of footer

### PR DESCRIPTION
**Pull request by omarujawara**
Closes #7

### CODE REVIEW

**Review by RickyC0626 — CHANGES_REQUESTED** [review]
It may have been bad wording of the question, but it is stating to get the div that has a class called `footer` and remove `main` from it.

**Comment by omarujawara** [comment]
👍

**Review by RickyC0626 — CHANGES_REQUESTED** [review]
Make sure to check if the div has the class `footer` before removing `main` from it

**Review by RickyC0626 — APPROVED** [review]
👍

**Pull request merged**
